### ISSUE TITLE
Memory Issues when opening files.

### ISSUE THREAD

**Issue by stevendaniels** [roo-rb/roo-xls#4] opened 2015-04-25 07:26 UTC
There have been problems reported when opening Excel files like [this one](https://freedomhouse.org/sites/default/files/FOTP2014%20Detailed%20Data%20and%20Subscores%201980-2014.xls) from Freedom House.

Code that causes the memory growth (roo-1.13.2):

``` ruby
require 'roo'
require 'uri'  # Needed to prevent a NameError on URI

# Where the xls is a renamed copy of the mentioned sheet ...
sheet = Roo::Spreadsheet.open('freedomhouse-press.xls')
```

See: 
https://github.com/roo-rb/roo/issues/179
https://github.com/roo-rb/roo/issues/168

**Comment by AlfonsoUceda** [comment] 2016-04-04 17:30
Hi @stevendaniels thanks for your work, I was wondering if you figured out something related this leak because I'm affected by it.

**Comment by tgturner** [comment] 2018-09-17 20:15
duplicate of issues in roo base

**Closed as completed by tgturner** 2018-09-17 20:15 UTC
